num_vec <- c(1, 2.5, 3, 4.8)
char_vec <- c("apple", "banana", "mango")
log_vec <- c(TRUE, FALSE, TRUE, TRUE)
print(num_vec)
print(char_vec)
print(log_vec)
print(class(num_vec))
print(class(char_vec))
print(class(log_vec))
